#!/bin/bash
touch ADUGODI.json
touch ANJANAPURA.json
touch ARAKERE.json
touch ATTIGUPPE.json
touch BASAVESHWARANAGAR.json
touch BASAVANAGUDI.json
touch BTM_LAYOUT.json
touch BANASHANKARI_2ND_STAGE.json
touch BYRASANDRA.json
touch CHAMRAJPET.json
touch CHIKKALA SANDRA.json
touch CV_RAMANNAGAR.json
touch DASARAHALLI.json
touch DOMLUR.json
touch EJIPURA.json
touch GANESH_MANDIRA.json
touch GIRINAGAR.json
touch HAMPINAGAR.json
touch HANUMANTHANAGAR.json
touch HEBBAL.json
touch HOODI.json
touch HOSAKEREHALLI.json
touch HSR_LAYOUT.json
touch JAYANAGAR.json
touch JEEVANBHIMANAGAR.json
touch JP_NAGAR.json
touch KANISANDRA.json
touch KATRIGUPPE.json
touch KENGERI.json
touch KONANKUNTE.json
touch KORAMANGALA.json
touch KUMARASWAMY_LAYOUT.json
touch LAKKASANDRA.json
touch MAHALAKSHMIPURAM.json
touch MALLESWARAM.json
touch MARATHAHALLI.json
touch NAGARBHAVI.json
touch PADMANABHANAGAR.json
touch PATTABHINAGAAR.json
touch PUTTENAHALLI.json
touch RAJAJRAJESWARINAGAR.json
touch RAJAJI_NAGAR.json
touch SARAKKI.json
touch SHAKAMBARI_NAGAR.json
touch SRI_NAGAR
touch SHANTHI_NAGAR
touch UTTARAHALLI
touch VASANTHNAGAR
touch VIDYAPEETA
touch VIJAYNAGARA
touch VIJINAPURA
touch YELACHENAHALLI
touch YEDIYUR 
